version: '3.9'
services:
  reportes-service:
    build: ./src/Tostao.ReportesService
    container_name: tostao_reportes
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__GetionDocumentalTostaoBD=Server=sqlserver;Database=GetionDocumentalTostaoBD;User Id=sa;Password=12345;TrustServerCertificate=True;
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tostao_sqlserver|
    environment:
      SA_PASSWORD: "12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
